export const CONSTANTS = {

    SIGNIN_REQUESTED: 'SIGNIN_REQUESTED',
    SIGNIN_SUCCEEDED: 'SIGNIN_SUCCEEDED',
    SIGNIN_FAILED: 'SIGNIN_FAILED',

    SIGNUP_REQUESTED: 'SIGNUP_REQUESTED',
    SIGNUP_SUCCEEDED: 'SIGNUP_SUCCEEDED',
    SIGNUP_FAILED: 'SIGNUP_FAILED',

    SIGNOUT_REQUESTED: 'SIGNOUT_REQUESTED',
    SIGNOUT_SUCCEEDED: 'SIGNOUT_SUCCEEDED',
    SIGNOUT_FAILED: 'SIGNOUT_FAILED',

    RESTAURENT_GET_REQUEST: 'RESTAURENT_GET_REQUEST',
    RESTAURENT_GET_SUCCESS: 'RESTAURENT_GET_SUCCESS',    
    RESTAURENT_GET_FAILURE: 'RESTAURENT_GET_FAILURE',
}